"""Jeux de données fictifs utilisés exclusivement par le prototype."""

SITES = [
    {
        "id": "GEN-042",
        "name": "Centre nautique",
        "area": "Agnettes",
        "category": "sport",
        "energy": ["electricite", "gaz"],
        "monthly_mwh": 186.4,
        "normalized_variance_pct": 14.8,
        "status": "derive",
        "drift_score": 88,
        "data_points": 28,
        "carbon_tco2e": 21.4,
        "completeness_pct": 98,
    },
    {
        "id": "GEN-017",
        "name": "Hôtel de Ville",
        "area": "Village",
        "category": "municipal",
        "energy": ["electricite", "reseau_chaleur"],
        "monthly_mwh": 142.7,
        "normalized_variance_pct": 8.3,
        "status": "surveillance",
        "drift_score": 76,
        "data_points": 46,
        "carbon_tco2e": 15.8,
        "completeness_pct": 99,
    },
    {
        "id": "GEN-088",
        "name": "École des Grésillons",
        "area": "Grésillons",
        "category": "school",
        "energy": ["electricite", "gaz"],
        "monthly_mwh": 94.2,
        "normalized_variance_pct": 5.9,
        "status": "surveillance",
        "drift_score": 69,
        "data_points": 18,
        "carbon_tco2e": 12.1,
        "completeness_pct": 95,
    },
    {
        "id": "GEN-061",
        "name": "Gymnase Jean Guimier",
        "area": "Luth",
        "category": "sport",
        "energy": ["electricite", "gaz"],
        "monthly_mwh": 71.8,
        "normalized_variance_pct": -7.4,
        "status": "cible",
        "drift_score": 38,
        "data_points": 21,
        "carbon_tco2e": 8.7,
        "completeness_pct": 97,
    },
    {
        "id": "GEN-103",
        "name": "Médiathèque François Rabelais",
        "area": "Centre",
        "category": "municipal",
        "energy": ["electricite", "reseau_chaleur"],
        "monthly_mwh": 58.1,
        "normalized_variance_pct": -3.2,
        "status": "cible",
        "drift_score": 31,
        "data_points": 16,
        "carbon_tco2e": 4.2,
        "completeness_pct": 100,
    },
    {
        "id": "GEN-121",
        "name": "Éclairage public — Agnettes",
        "area": "Agnettes",
        "category": "lighting",
        "energy": ["electricite"],
        "monthly_mwh": 47.6,
        "normalized_variance_pct": 11.2,
        "status": "derive",
        "drift_score": 81,
        "data_points": 74,
        "carbon_tco2e": 2.4,
        "completeness_pct": 93,
    },
    {
        "id": "GEN-076",
        "name": "Groupe scolaire Anatole France",
        "area": "Fossé-de-l’Aumône",
        "category": "school",
        "energy": ["electricite", "gaz"],
        "monthly_mwh": 82.3,
        "normalized_variance_pct": -4.7,
        "status": "cible",
        "drift_score": 33,
        "data_points": 24,
        "carbon_tco2e": 9.6,
        "completeness_pct": 98,
    },
    {
        "id": "GEN-009",
        "name": "Centre administratif",
        "area": "Village",
        "category": "municipal",
        "energy": ["electricite", "reseau_chaleur"],
        "monthly_mwh": 108.9,
        "normalized_variance_pct": 2.1,
        "status": "stable",
        "drift_score": 45,
        "data_points": 31,
        "carbon_tco2e": 10.9,
        "completeness_pct": 99,
    },
]

INVOICES = [
    {
        "id": "EN-2608431",
        "provider": "EDF Collectivités",
        "site": "Centre nautique",
        "period": "2026-08",
        "amount_ttc_eur": 28471.20,
        "match_pct": 99,
        "payment_status": "paid",
    },
    {
        "id": "GR-9430872",
        "provider": "ENGIE",
        "site": "École des Grésillons",
        "period": "2026-08",
        "amount_ttc_eur": 12845.70,
        "match_pct": 82,
        "payment_status": "anomaly",
    },
    {
        "id": "RC-2209684",
        "provider": "Gennevilliers Énergie",
        "site": "Hôtel de Ville",
        "period": "2026-08",
        "amount_ttc_eur": 19630.40,
        "match_pct": 100,
        "payment_status": "pending",
    },
    {
        "id": "EA-1703258",
        "provider": "Suez",
        "site": "Gymnase Jean Guimier",
        "period": "2026-07",
        "amount_ttc_eur": 3184.93,
        "match_pct": 97,
        "payment_status": "paid",
    },
]

ALERTS = [
    {
        "id": 1,
        "level": "critical",
        "title": "Puissance nocturne anormale",
        "site": "Centre nautique",
        "description": "Charge de base supérieure de 42 % depuis trois nuits.",
        "source": ["enedis", "gtb"],
        "value": 286,
        "unit": "kW",
    },
    {
        "id": 2,
        "level": "critical",
        "title": "Écart facture / index",
        "site": "École des Grésillons",
        "description": "1 842 € non expliqués sur la période.",
        "source": ["grdf", "invoice"],
        "value": 1842,
        "unit": "EUR",
    },
    {
        "id": 3,
        "level": "warning",
        "title": "Consommation d’eau continue",
        "site": "Gymnase Jean Guimier",
        "description": "Débit de 0,31 m³/h en dehors des heures d’occupation.",
        "source": ["suez"],
        "value": 0.31,
        "unit": "m3/h",
    },
]

INTEGRATIONS = [
    {"name": "Enedis", "status": "connected", "scope": "253 PDL — courbes et index"},
    {"name": "GRDF", "status": "connected", "scope": "40 PCE — consommations"},
    {"name": "Suez", "status": "connected", "scope": "118 compteurs d’eau"},
    {"name": "OPERAT", "status": "connected", "scope": "déclarations et objectifs"},
    {"name": "Orange Live Objects", "status": "connected", "scope": "capteurs IoT"},
    {"name": "Sigfox", "status": "warning", "scope": "2 objets à vérifier"},
]

FORECASTS = {
    "low": {
        "label": "sobriete",
        "annual_cost_meur": 4.31,
        "budget_variance_pct": -8.4,
        "monthly_cost_keur": [405, 371, 342, 317, 281, 268, 265, 274, 299, 348, 383, 421],
    },
    "central": {
        "label": "central",
        "annual_cost_meur": 4.86,
        "budget_variance_pct": 3.2,
        "monthly_cost_keur": [452, 421, 387, 348, 313, 297, 294, 306, 337, 394, 438, 482],
    },
    "stress": {
        "label": "tension",
        "annual_cost_meur": 5.42,
        "budget_variance_pct": 15.0,
        "monthly_cost_keur": [501, 472, 431, 389, 354, 332, 329, 343, 377, 439, 491, 548],
    },
}

SAMPLE_CONSUMPTIONS = [
    {
        "site_id": "GEN-042",
        "point_id": "PDL-253",
        "timestamp": "2026-09-12T10:30:00+02:00",
        "value": 286.4,
        "unit": "kWh",
    },
    {
        "site_id": "GEN-017",
        "point_id": "PCE-040",
        "timestamp": "2026-09-12T10:30:00+02:00",
        "value": 81.2,
        "unit": "kWh",
    },
    {
        "site_id": "GEN-088",
        "point_id": "EAU-118",
        "timestamp": "2026-09-12T10:30:00+02:00",
        "value": 2.34,
        "unit": "m3",
    },
]
